mail.host=smtp.gmail.com
mail.port=587
mail.protocol=smtp
mail.auth=true
mail.starttls.enable=true
mail.username=ttohahamail@gmail.com
mail.password=giptfzreyhlogoqe
mail.from.address=ttohahamail@gmail.com
mail.from.name=MyJavaApp
mail.confirmation.subject=Confirm your registration
mail.confirmation.base.url=http://localhost:8080/blinov_first_war_exploded/controller?command=confirm_email&token=
mail.dev.mode=false
mail.smtp.ssl.trust=smtp.gmail.com