telegram.bot.token=8501678330:AAHuyRe5FbW3Z-f9v0gMMLbYGYrSVIo9jO4
telegram.bot.username=myphonebook_confirm_bot
telegram.polling.timeout=25
telegram.confirmation.base.url=http://localhost:8080/blinov_first_war_exploded
